# Generated by Django 5.2.14 on 2026-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_team_id_alter_teammember_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('qa', 'QA'), ('customer', 'CUSTOMER')], max_length=15),
        ),
    ]
