# Generated by Django 5.2.14 on 2026-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarmotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('qa', 'QA'), ('customer', 'Customer'), ('traders', 'Traders')], default='traders', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('broker', models.CharField(blank=True, choices=[('fyers', 'FYERS'), ('dhan', 'DHAN')], max_length=20, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_freeze', models.BooleanField(default=False)),
                ('final_freeze', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('trade_eligibility', models.BooleanField(default=True)),
                ('pl_integer', models.DecimalField(decimal_places=2, default=0.0, help_text='Current P&L value', max_digits=12)),
                ('stats', models.CharField(choices=[('profit', 'PROFIT'), ('loss', 'LOSS'), ('no_trade', 'NO TRADE'), ('neutral', 'NEUTRAL'), ('heavy_loss', 'HEAVY LOSS'), ('heavy_profit', 'HEAVY PROFIT')], default='no_trade', max_length=20)),
                ('primary_freeze_time', models.DateTimeField(blank=True, null=True)),
                ('primary_freeze_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_freeze_time', models.DateTimeField(blank=True, null=True)),
                ('final_freeze_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('developer', 'Developer'), ('qa', 'QA'), ('customer', 'Customer'), ('traders', 'Traders')], max_length=15),
        ),
    ]
