# Generated by Django 5.2.14 on 2026-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_marmotuser_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marmotuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('developer', 'Developer'), ('customer', 'Customer'), ('traders', 'Traders')], default='traders', max_length=20),
        ),
    ]
