from django.urls import path
from .views import (
    LoginView,
    SignUpView,
    VerifyOtpView,
    ResendOtpView,
    EmailSsoLoginView,
    MarmotPasswordResetView,
    MarmotPasswordResetDoneView,
    MarmotPasswordResetConfirmView,
    MarmotPasswordResetCompleteView,
    UserDashboardView,
    UserLiveDashboardView,
    UserSandboxDashboardView,
    UserAIDashboardView,
    UserTerminalView,
    UserJournalView,
    UserBacktestView,
    UserBacktestCreateView,
    UserBacktestDetailView,
    UserBackupListView,
    UserBackupCreateView,
    UserBackupDownloadView,
    UserEnvironmentToggleView,
    UserEnvironmentToggleModalView,
    UserAccountSelectView,
    UserAccountCreateModalView,
    UserAccountCreateView,
    UserAccountEditModalView,
    UserAccountEditView,
    UserAccountsCardsView,
    UserAccountTestAuthView,
    UserAccountSetDefaultView,
    UserAccountDeleteView,
    UserAccountConsentModalView,
    UserAccountRefreshTokenView,
    UserAccountTotpTokenView,
    UserAccountSettingsView,
    UserKillSwitchView,
    LogoutView,
    UserProfileView,
    UserProfilePasswordChangeView
)

app_name = 'users'

urlpatterns = [
    # Authentication & Onboarding
    path('login/', LoginView.as_view(), name='marmot-login'),
    path('signup/', SignUpView.as_view(), name='marmot-signup'),
    path('verify-otp/', VerifyOtpView.as_view(), name='marmot-verify-otp'),
    path('resend-otp/', ResendOtpView.as_view(), name='marmot-resend-otp'),
    path('email-login/', EmailSsoLoginView.as_view(), name='marmot-email-sso'),
    path('reset-password/', MarmotPasswordResetView.as_view(), name='marmot-reset-password'),
    path('reset-password/done/', MarmotPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', MarmotPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', MarmotPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # User Dashboards & Terminal Operations
    path('terminal/', UserTerminalView.as_view(), name='user-terminal'),
    path('dashboard/', UserDashboardView.as_view(), name='marmot-dashboard'),
    path('dashboard/live/', UserLiveDashboardView.as_view(), name='user-live-dashboard'),
    path('dashboard/sandbox/', UserSandboxDashboardView.as_view(), name='user-sandbox-dashboard'),
    path('dashboard/ai/', UserAIDashboardView.as_view(), name='user-ai-dashboard'),

    path('journal/', UserJournalView.as_view(), name='user-journal'),
    path('backtest/', UserBacktestView.as_view(), name='user-backtest'),
    path('backtest/create/', UserBacktestCreateView.as_view(), name='user-backtest-create'),
    path('backtest/<int:pk>/', UserBacktestDetailView.as_view(), name='user-backtest-detail'),
    path('backup/', UserBackupListView.as_view(), name='user-backup'),
    path('backup/', UserBackupListView.as_view(), name='user-backup-list'),
    path('backup/create/', UserBackupCreateView.as_view(), name='user-backup-create'),
    path('backup/<int:pk>/download/', UserBackupDownloadView.as_view(), name='user-backup-download'),
    path('account/select/', UserAccountSelectView.as_view(), name='user-account-select'),
    path('account/create-modal/', UserAccountCreateModalView.as_view(), name='user-account-create-modal'),
    path('account/create/', UserAccountCreateView.as_view(), name='user-account-create'),
    path('account/<int:pk>/edit-modal/', UserAccountEditModalView.as_view(), name='user-account-edit-modal'),
    path('account/<int:pk>/edit/', UserAccountEditView.as_view(), name='user-account-edit'),
    path('account/cards/', UserAccountsCardsView.as_view(), name='user-accounts-cards'),
    path('account/<int:pk>/test-auth/', UserAccountTestAuthView.as_view(), name='user-account-test-auth'),
    path('account/<int:pk>/set-default/', UserAccountSetDefaultView.as_view(), name='user-account-set-default'),
    path('account/<int:pk>/delete/', UserAccountDeleteView.as_view(), name='user-account-delete'),
    path('account/<int:pk>/consent-modal/', UserAccountConsentModalView.as_view(), name='user-account-consent-modal'),
    path('account/<int:pk>/totp-token/', UserAccountTotpTokenView.as_view(), name='user-account-totp-token'),
    path('account/<int:pk>/refresh-token/', UserAccountRefreshTokenView.as_view(), name='user-account-refresh-token'),
    path('environment/toggle/', UserEnvironmentToggleView.as_view(), name='user-env-toggle'),
    path('environment/toggle-modal/', UserEnvironmentToggleModalView.as_view(), name='user-env-toggle-modal'),
    path('accounts/', UserAccountSettingsView.as_view(), name='user-accounts'),
    path('accounts/sandbox/', UserAccountSettingsView.as_view(), name='user-sandbox'),
    path('kill-switch/', UserKillSwitchView.as_view(), name='user-kill-switch'),
    path('logout/', LogoutView.as_view(), name='marmot-logout'),
    path('profile/', UserProfileView.as_view(), name='marmot-profile'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='marmot-profile-user'),
    path('profile/change-password/', UserProfilePasswordChangeView.as_view(), name='marmot-profile-password'),
]