# Generated by Django 5.2.14 on 2026-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Start date for options data range')),
                ('end_date', models.DateField(help_text='End date for options data range')),
                ('market_type', models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Market segment: INDEX/F&O (India) or FOREX/Futures (CME Micros)', max_length=20)),
                ('index_name', models.CharField(blank=True, choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('SENSEX', 'BSE Sensex'), ('GIFTNIFTY', 'GIFT Nifty'), ('INDIAVIX', 'India VIX')], default='NIFTY', help_text='Target trading index (INDEX/F&O only)', max_length=50, null=True)),
                ('strike_count', models.PositiveIntegerField(blank=True, default=5, help_text='Number of strikes above/below ATM (INDEX/F&O only)', null=True)),
                ('forex_instrument', models.CharField(blank=True, choices=[('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], help_text='CME Micro Futures instrument to back up (FOREX/FUTURES only)', max_length=10, null=True)),
                ('databento_schema', models.CharField(blank=True, choices=[('ohlcv-1m', '1-Min Candles (OHLCV)'), ('trades', 'Tick-by-Tick Executions'), ('mbp-10', 'Level-10 Order Book Depth (DOM)'), ('mbo', 'Full Market-By-Order Flow')], default='ohlcv-1m', help_text='Databento Order Flow schema (FOREX/FUTURES only)', max_length=20, null=True)),
                ('is_macro_assist', models.BooleanField(default=False, help_text='Designates this dataset as an AI Macro & Fundamental sentiment backup')),
                ('macro_timeframe', models.CharField(blank=True, choices=[('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour (Recommended)'), ('1d', '1 Day (EOD)')], default='1h', help_text='Macro interval (default 1h)', max_length=10, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Execution progress percentage from 0 to 100')),
                ('parquet_file_path', models.CharField(blank=True, help_text='Local path to the saved Parquet files', max_length=500, null=True)),
                ('file_size_mb', models.FloatField(default=0.0, help_text='Generated Parquet storage size in MB')),
                ('error_logs', models.TextField(blank=True, help_text='Timestamped trace and error messages if the job fails', null=True)),
            ],
            options={
                'verbose_name': 'Market Backup Task',
                'verbose_name_plural': 'Market Backup Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
