# Generated by Django 5.2.14 on 2026-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Start date for options data range')),
                ('end_date', models.DateField(help_text='End date for options data range')),
                ('index_name', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty')], default='NIFTY', help_text='Target trading index', max_length=50)),
                ('strike_count', models.PositiveIntegerField(default=5, help_text='Number of strikes above/below ATM')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Execution progress percentage from 0 to 100')),
                ('parquet_file_path', models.CharField(blank=True, help_text='Local path to the saved Parquet files', max_length=500, null=True)),
                ('file_size_mb', models.FloatField(default=0.0, help_text='Generated Parquet storage size in MB')),
                ('error_logs', models.TextField(blank=True, help_text='Timestamped trace and error messages if the job fails', null=True)),
            ],
            options={
                'verbose_name': 'Market Backup Task',
                'verbose_name_plural': 'Market Backup Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
