# Generated by Django 5.2.14 on 2026-09-19 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketbackuptask',
            name='linked_backup_task',
            field=models.ForeignKey(blank=True, help_text='Co-located market backup task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_backups', to='market.marketbackuptask'),
        ),
    ]
