# Generated by Django 5.2.14 on 2026-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='use_30_days_5s',
            field=models.BooleanField(default=False, help_text='Fetch 5S resolution data for 30-day window (INDEX/F&O only)'),
        ),
    ]
