# Generated by Django 5.2.14 on 2026-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketbackuptask_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbackuptask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=20),
        ),
    ]
