# Generated by Django 5.2.14 on 2026-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketbackuptask_use_30_days_5s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbackuptask',
            name='strike_count',
            field=models.PositiveIntegerField(blank=True, default=15, help_text='Number of strikes above/below ATM (INDEX/F&O only)', null=True),
        ),
    ]
