# Generated by Django 5.2.14 on 2026-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_marketbackuptask_strike_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbackuptask',
            name='use_30_days_5s',
            field=models.BooleanField(default=True, help_text='Fetch 5S resolution data (INDEX/F&O only)'),
        ),
    ]
