# Generated by Django 5.2.14 on 2026-08-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_backtesttask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BacktestTask',
        ),
    ]
