# Generated by Django 5.2.14 on 2026-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_delete_backtesttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbackuptask',
            name='index_name',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('INDIAVIX', 'India VIX')], default='NIFTY', help_text='Target trading index', max_length=50),
        ),
    ]
