# Generated by Django 5.2.14 on 2026-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_marketbackuptask_use_30_days_5s'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='use_30_days_1s',
            field=models.BooleanField(default=False, help_text='Fetch 1S resolution data (INDEX/F&O only)'),
        ),
    ]
