# Generated by Django 5.2.14 on 2026-08-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_marketbackuptask_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='forex_instrument',
            field=models.CharField(blank=True, choices=[('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], help_text='CME Micro Futures instrument to back up (FOREX/FUTURES only)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marketbackuptask',
            name='market_type',
            field=models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Market segment: INDEX/F&O (India) or FOREX/Futures (CME Micros)', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketbackuptask',
            name='index_name',
            field=models.CharField(blank=True, choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('INDIAVIX', 'India VIX')], default='NIFTY', help_text='Target trading index (INDEX/F&O only)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketbackuptask',
            name='strike_count',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Number of strikes above/below ATM (INDEX/F&O only)', null=True),
        ),
    ]
