# Generated by Django 5.2.14 on 2026-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_add_market_type_forex_to_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='databento_schema',
            field=models.CharField(blank=True, choices=[('ohlcv-1m', '1-Min Candles (OHLCV)'), ('trades', 'Tick-by-Tick Executions'), ('mbp-10', 'Level-10 Order Book Depth (DOM)'), ('mbo', 'Full Market-By-Order Flow')], default='ohlcv-1m', help_text='Databento Order Flow schema (FOREX/FUTURES only)', max_length=20, null=True),
        ),
    ]
