# Generated by Django 5.2.14 on 2026-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_marketbackuptask_databento_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbackuptask',
            name='index_name',
            field=models.CharField(blank=True, choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('SENSEX', 'BSE Sensex'), ('GIFTNIFTY', 'GIFT Nifty'), ('INDIAVIX', 'India VIX')], default='NIFTY', help_text='Target trading index (INDEX/F&O only)', max_length=50, null=True),
        ),
    ]
