# Generated by Django 5.2.14 on 2026-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_marketbackuptask_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='is_macro_assist',
            field=models.BooleanField(default=False, help_text='Designates this dataset as an AI Macro & Fundamental sentiment backup'),
        ),
        migrations.AddField(
            model_name='marketbackuptask',
            name='macro_timeframe',
            field=models.CharField(blank=True, choices=[('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour (Recommended)'), ('1d', '1 Day (EOD)')], default='1h', help_text='Macro interval (default 1h)', max_length=10, null=True),
        ),
    ]
