# Generated by Django 5.2.14 on 2026-09-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_marketbackuptask_is_macro_assist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbackuptask',
            name='linked_backup_task',
            field=models.ForeignKey(blank=True, help_text='Co-located market backup task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_backups', to='market.marketbackuptask'),
        ),
    ]
