# Generated by Django 5.2.14 on 2026-07-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_marmotuser_alter_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeExecConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master toggle to enable or disable auto trade execution features')),
                ('max_loss_limit', models.DecimalField(decimal_places=2, help_text='Maximum allowed loss limit before auto-freeze triggers', max_digits=12)),
                ('max_profit_limit', models.DecimalField(decimal_places=2, help_text='Target max profit limit for the session', max_digits=12)),
                ('auto_lot_status', models.BooleanField(default=False, help_text='Enable automatic lot size calculation based on risk parameters')),
                ('default_lot_size', models.PositiveIntegerField(default=1, help_text='Default lot size to use when auto lot status is disabled')),
                ('auto_sl_status', models.BooleanField(default=False, help_text='Automatically attach default stop loss to outgoing orders')),
                ('default_risk_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Default risk value (e.g. 1.5% or 50 points depending on risk type)', max_digits=10)),
                ('default_risk_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed_amount', 'Fixed Amount (₹/$)'), ('points', 'Points')], default='percentage', help_text='Calculation mode for default stop loss risk', max_length=20)),
                ('layer_status', models.BooleanField(default=False, help_text='Enable order layering (pyramiding into winning positions)')),
                ('layer_add_in_lot_count', models.PositiveSmallIntegerField(default=0, help_text='Number of additional lots to add per layer entry')),
                ('layer_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage step/distance required to trigger each layer entry', max_digits=5)),
                ('forecast_status', models.BooleanField(default=False, help_text='Enable algorithmic predictive forecasting for position entries')),
                ('backtest_status', models.BooleanField(default=False, help_text='Enable backtest execution simulation mode')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marmot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exec_config', to='users.marmotuser', verbose_name='Marmot User')),
            ],
            options={
                'verbose_name': 'Trade Execution Configuration',
                'verbose_name_plural': 'Trade Execution Configurations',
            },
        ),
    ]
