# Generated by Django 5.2.14 on 2026-09-19 06:12

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(db_index=True, help_text='Session or conversation identifier', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Message text or generated markdown')),
                ('model_name', models.CharField(default='gemini-3.6-flash', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(default='DHAN', help_text='Broker origin e.g. DHAN, FYERS', max_length=50)),
                ('broker_client_id', models.CharField(blank=True, db_index=True, help_text='Generic Broker Client ID', max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, help_text='Broker Order ID', max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, help_text='Trading Symbol e.g. NIFTY-Jan2024-21500-CE', max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, help_text='Order Status e.g. TRADED, CANCELLED', max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='BUY / SELL', max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Order Quantity')),
                ('price', models.FloatField(default=0.0, help_text='Execution Price')),
                ('payload', models.JSONField(default=dict, help_text='Complete raw webhook JSON payload')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Postback Log',
                'verbose_name_plural': 'Postback Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand_name', models.CharField(default='Marmot', help_text='Platform brand name', max_length=100)),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark theme logo (.svg, .png, .jpg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('logo_light', models.ImageField(blank=True, help_text='Light theme logo (.svg, .png, .jpg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('favicon', models.ImageField(blank=True, help_text='Favicon icon (.ico, .png, .svg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('banner_video', models.FileField(blank=True, help_text='Home banner hero video (.mp4, .webm, .mov)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('meta_config', models.JSONField(blank=True, default=dict, help_text='Extensible metadata & SEO configuration')),
                ('fyers_app_id', models.CharField(blank=True, default='', help_text='FYERS App ID (e.g. XC12345-100)', max_length=255)),
                ('fyers_secret_key', models.CharField(blank=True, default='', help_text='FYERS App Secret Key', max_length=255)),
                ('fyers_access_token', models.TextField(blank=True, default='', help_text='FYERS Valid Live Access Token')),
                ('fyers_redirect_uri', models.CharField(blank=True, default='https://trade.marmot.com/fyers/callback', help_text='FYERS OAuth Redirect URI', max_length=255)),
                ('fyers_token_generated_date', models.DateField(blank=True, help_text='Date when FYERS token was generated', null=True)),
                ('fyers_feed_is_active', models.BooleanField(default=False, help_text='Toggle to stream live market quotes from FYERS')),
                ('live_execution_master_switch', models.BooleanField(default=False, help_text='Global master toggle for live algorithmic order execution')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
