# Generated by Django 5.2.14 on 2026-08-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(default='DHAN', help_text='Broker origin e.g. DHAN, FYERS', max_length=50)),
                ('order_id', models.CharField(blank=True, help_text='Broker Order ID', max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, help_text='Trading Symbol e.g. NIFTY-Jan2024-21500-CE', max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, help_text='Order Status e.g. TRADED, CANCELLED', max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='BUY / SELL', max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Order Quantity')),
                ('price', models.FloatField(default=0.0, help_text='Execution Price')),
                ('payload', models.JSONField(default=dict, help_text='Complete raw webhook JSON payload')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the postback webhook', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postback_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postback Log',
                'verbose_name_plural': 'Postback Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
