# Generated by Django 5.2.14 on 2026-08-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbacklog',
            name='dhan_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique Dhan Client ID e.g. 1000000001', max_length=100, null=True),
        ),
    ]
