# Generated by Django 5.2.14 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_postbacklog_dhan_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postbacklog',
            name='dhan_client_id',
        ),
        migrations.AddField(
            model_name='postbacklog',
            name='broker_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Generic Broker Client ID', max_length=100, null=True),
        ),
    ]
