# Generated by Django 5.2.14 on 2026-08-29 07:34

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_postbacklog_dhan_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand_name', models.CharField(default='Marmot', help_text='Platform brand name', max_length=100)),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark theme logo (.svg, .png, .jpg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('logo_light', models.ImageField(blank=True, help_text='Light theme logo (.svg, .png, .jpg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('favicon', models.ImageField(blank=True, help_text='Favicon icon (.ico, .png, .svg)', null=True, upload_to=apps.common.models.site_setting_logo_path)),
                ('meta_config', models.JSONField(blank=True, default=dict, help_text='Extensible metadata & SEO configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
