# Generated by Django 5.2.14 on 2026-09-02 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(db_index=True, help_text='Session or conversation identifier', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Message text or generated markdown')),
                ('model_name', models.CharField(default='gemini-3.6-flash', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='common_aich_session_908213_idx'), models.Index(fields=['user', 'session_id', 'created_at'], name='common_aich_user_id_6723ee_idx')],
            },
        ),
    ]
