# Generated by Django 5.2.14 on 2026-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_access_token',
            field=models.TextField(blank=True, default='', help_text='FYERS Valid Live Access Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_app_id',
            field=models.CharField(blank=True, default='', help_text='FYERS App ID (e.g. XC12345-100)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_feed_is_active',
            field=models.BooleanField(default=False, help_text='Toggle to stream live market quotes from FYERS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_redirect_uri',
            field=models.CharField(blank=True, default='https://trade.marmot.com/fyers/callback', help_text='FYERS OAuth Redirect URI', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_secret_key',
            field=models.CharField(blank=True, default='', help_text='FYERS App Secret Key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fyers_token_generated_date',
            field=models.DateField(blank=True, help_text='Date when FYERS token was generated', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='live_execution_master_switch',
            field=models.BooleanField(default=False, help_text='Global master toggle for live algorithmic order execution'),
        ),
    ]
