# Generated by Django 5.2.14 on 2026-09-10 14:57

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_sitesettings_fyers_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_video',
            field=models.FileField(blank=True, help_text='Home banner hero video (.mp4, .webm, .mov)', null=True, upload_to=apps.common.models.site_setting_logo_path),
        ),
    ]
