# Generated by Django 5.2.14 on 2026-08-02 12:58

import apps.common.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('developer', 'Developer'), ('customer', 'Customer'), ('traders', 'Traders')], default='traders', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('broker', models.CharField(blank=True, choices=[('fyers', 'FYERS'), ('dhan', 'DHAN')], max_length=20, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_freeze', models.BooleanField(default=False)),
                ('final_freeze', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('trade_eligibility', models.BooleanField(default=True)),
                ('pl_integer', models.DecimalField(decimal_places=2, default=0.0, help_text='Current P&L value', max_digits=12)),
                ('stats', models.CharField(choices=[('profit', 'PROFIT'), ('loss', 'LOSS'), ('no_trade', 'NO TRADE'), ('neutral', 'NEUTRAL'), ('heavy_loss', 'HEAVY LOSS'), ('heavy_profit', 'HEAVY PROFIT')], default='no_trade', max_length=20)),
                ('primary_freeze_time', models.DateTimeField(blank=True, null=True)),
                ('primary_freeze_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_freeze_time', models.DateTimeField(blank=True, null=True)),
                ('final_freeze_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.common.models.SoftDeleteUserModelManager()),
                ('all_objects', apps.common.models.SoftDeleteUserModelManager(with_deleted=True)),
            ],
        ),
    ]
