# Generated by Django 5.2.14 on 2026-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('developer', 'Developer'), ('customer', 'Customer'), ('traders', 'Traders'), ('member', 'Member')], default='traders', max_length=20),
        ),
    ]
