# Generated by Django 5.2.14 on 2026-10-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='final_freeze_pl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='final_freeze_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_freeze_pl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_freeze_time',
        ),
    ]
