# Generated by Django 5.2.14 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dhan_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dhan_client_id',
        ),
        migrations.AddField(
            model_name='user',
            name='broker_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Generic Broker Client ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, help_text='Generic Broker API Key / Secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='app_id',
            field=models.CharField(blank=True, help_text='Generic Broker App ID / Client Secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='broker',
            field=models.CharField(blank=True, choices=[('fyers', 'FYERS'), ('dhan', 'DHAN')], default='dhan', max_length=20, null=True),
        ),
    ]
