# Generated by Django 5.2.14 on 2026-08-09 15:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_dhan_client_id_user_broker_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture stored on Cloudinary', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
