# Generated by Django 5.2.14 on 2026-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_live_configured',
            field=models.BooleanField(default=False, help_text='Live broker credentials configured'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_live_enabled',
            field=models.BooleanField(default=False, help_text='Live real-money trading mode enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_live_trader_active',
            field=models.BooleanField(default=False, help_text='Live real-time trader active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sandbox_configured',
            field=models.BooleanField(default=False, help_text='Sandbox environment credentials configured'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sandbox_enabled',
            field=models.BooleanField(default=True, help_text='Sandbox paper-trading mode enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sandbox_trader_active',
            field=models.BooleanField(default=False, help_text='Sandbox real-time trader active'),
        ),
    ]
