# Generated by Django 5.2.14 on 2026-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_live_configured_user_is_live_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watching_on',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account')], default='SANDBOX', help_text='Current global watching environment mode (LIVE / SANDBOX)', max_length=20),
        ),
    ]
