# Generated by Django 5.2.14 on 2026-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_watching_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='broker_client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_live_configured',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_live_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_live_trader_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sandbox_configured',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sandbox_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sandbox_trader_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watching_on',
        ),
    ]
