# Generated by Django 5.2.14 on 2026-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_engine', '0002_alter_tradeexecconfig_marmot_user'),
        ('users', '0008_marmotuser_email_marmotuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarmotUser',
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='broker',
            field=models.CharField(blank=True, choices=[('fyers', 'FYERS'), ('dhan', 'DHAN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='final_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='final_freeze_pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='final_freeze_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pl_integer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current P&L value', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_freeze_pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_freeze_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('developer', 'Developer'), ('customer', 'Customer'), ('traders', 'Traders')], default='traders', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='stats',
            field=models.CharField(choices=[('profit', 'PROFIT'), ('loss', 'LOSS'), ('no_trade', 'NO TRADE'), ('neutral', 'NEUTRAL'), ('heavy_loss', 'HEAVY LOSS'), ('heavy_profit', 'HEAVY PROFIT')], default='no_trade', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_eligibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('developer', 'Developer'), ('customer', 'Customer'), ('traders', 'Traders')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
