# Generated by Django 5.2.14 on 2026-08-02 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='marmot_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exec_config', to=settings.AUTH_USER_MODEL, verbose_name='Marmot User'),
        ),
    ]
