# Generated by Django 5.2.14 on 2026-10-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeExecConfig',
        ),
    ]
