# Generated by Django 5.2.14 on 2026-09-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest', '0002_initial'),
        ('trade_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brokermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_portfolio_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Trader'),
        ),
        migrations.AddField(
            model_name='livestrategy',
            name='backtest_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_deployments', to='backtest.backtesttask', verbose_name='Source Backtest'),
        ),
        migrations.AddField(
            model_name='livestrategy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestrategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_strategies', to=settings.AUTH_USER_MODEL, verbose_name='Trader'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='admins_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_configs_exec', to=settings.AUTH_USER_MODEL, verbose_name='Marmot User'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertradingaccount',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='trade_config.brokermaster', verbose_name='Broker Platform'),
        ),
        migrations.AddField(
            model_name='usertradingaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertradingaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Trader'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='trade_config.usertradingaccount', verbose_name='Target Trading Account'),
        ),
        migrations.AddField(
            model_name='livestrategy',
            name='trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_strategies', to='trade_config.usertradingaccount', verbose_name='Target Trading Account'),
        ),
        migrations.AddField(
            model_name='dailyportfoliosnapshot',
            name='trading_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='trade_config.usertradingaccount', verbose_name='Trading Account'),
        ),
        migrations.AddConstraint(
            model_name='dailyportfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'trading_account', 'date'), name='unique_user_account_daily_snapshot'),
        ),
    ]
