# Generated by Django 5.2.14 on 2026-09-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestrategy',
            name='strategy_name',
            field=models.CharField(choices=[('quant_engine', 'Go Quantitative Rule Engine (ORB / SMC / Momentum)'), ('orb_momentum', 'Opening Range Breakout (ORB 15m) & Momentum'), ('ict_smc', 'ICT Smart Money Concepts (SMC v3)'), ('hft_scalp', 'High-Frequency Micro-Scalp (HFT 1:2.0)')], default='quant_engine', max_length=50),
        ),
    ]
