# Generated by Django 5.2.14 on 2026-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyportfoliosnapshot',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('MOCK', 'Mock Emulator Account')], default='MOCK', help_text='Execution Mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestrategy',
            name='execution_mode',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('MOCK', 'Mock Emulator Account')], default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('MOCK', 'Mock Emulator Account')], default='MOCK', help_text='Target execution account mode (LIVE / MOCK)', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertradingaccount',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('MOCK', 'Mock Emulator Account')], default='MOCK', help_text='Account environment mode (LIVE / MOCK)', max_length=20),
        ),
    ]
