# Generated by Django 5.2.14 on 2026-08-11 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0003_tradeexecconfig_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account')], default='SANDBOX', help_text='Target execution account mode (LIVE / SANDBOX)', max_length=20),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='api_response_log',
            field=models.JSONField(blank=True, default=dict, help_text='Live API response telemetry log for Sandbox & Live trades'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='estimated_brokerage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated brokerage & taxes incurred', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='execution_remarks',
            field=models.TextField(blank=True, help_text='Execution notes and strategy remarks', null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='execution_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='created', help_text='Realtime execution status', max_length=20),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='realtime_pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Realtime strategy execution PnL', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='admins_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_configs_exec', to=settings.AUTH_USER_MODEL, verbose_name='Marmot User'),
        ),
    ]
