# Generated by Django 5.2.14 on 2026-08-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0004_tradeexecconfig_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Broker Display Name (e.g. DHAN, FYERS, ZERODHA)', max_length=100)),
                ('code', models.CharField(help_text='Broker system code (e.g. dhan, fyers, sandbox)', max_length=50, unique=True)),
                ('api_base_url', models.URLField(blank=True, help_text='Base API Gateway URL for execution', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Broker availability toggle')),
                ('description', models.TextField(blank=True, help_text='Broker notes and integration details')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Broker',
                'verbose_name_plural': 'Master Brokers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(help_text='Account Nickname (e.g. Primary Dhan Live, Fyers Alpha, Sandbox Demo)', max_length=150)),
                ('account_type', models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account')], default='SANDBOX', help_text='Account environment mode (LIVE / SANDBOX)', max_length=20)),
                ('broker_client_id', models.CharField(blank=True, help_text='Broker Client ID / User ID', max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key / Token', max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, help_text='App ID / Secret Key', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default primary trading account for the user?')),
                ('is_active', models.BooleanField(default=True, help_text='Account active toggle')),
                ('is_configured', models.BooleanField(default=False, help_text='API key credentials validated')),
                ('is_trader_active', models.BooleanField(default=False, help_text='Real-time trading execution loop active for this account')),
                ('realtime_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Realtime account PnL', max_digits=12)),
                ('account_summary', models.JSONField(blank=True, default=dict, help_text='Live API Telemetry (balance, margin, positions, orders)')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='trade_config.brokermaster', verbose_name='Broker Platform')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'User Trading Account',
                'verbose_name_plural': 'User Trading Accounts',
                'ordering': ['-is_default', 'account_type', 'account_name'],
            },
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='trade_config.usertradingaccount', verbose_name='Target Trading Account'),
        ),
    ]
