# Generated by Django 5.2.14 on 2026-09-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0004_alter_livestrategy_strategy_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSessionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Custom name for this simulation session snapshot', max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text='Trader observations, market condition notes, or strategy rationale')),
                ('is_favorite', models.BooleanField(db_index=True, default=False, help_text='Favorite bookmark toggle')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ 1 Star'), (2, '⭐⭐ 2 Stars'), (3, '⭐⭐⭐ 3 Stars')], db_index=True, default=1)),
                ('sim_mode', models.CharField(default='BACKUP', help_text='Simulation mode (LIVE or BACKUP)', max_length=20)),
                ('dataset_file', models.CharField(blank=True, default='', help_text='Historical Parquet dataset file name if in replay mode', max_length=255)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Starting account capital', max_digits=14)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Ending available balance', max_digits=14)),
                ('gross_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross realized trading PnL', max_digits=14)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Net PnL after brokerage & statutory charges', max_digits=14)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Total brokerage and transaction charges', max_digits=14)),
                ('total_trades', models.PositiveIntegerField(default=0, help_text='Total completed trades in session')),
                ('winning_trades', models.PositiveIntegerField(default=0, help_text='Count of profitable trades')),
                ('losing_trades', models.PositiveIntegerField(default=0, help_text='Count of losing trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate percentage (0-100%)', max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, help_text='Peak drawdown in session', max_digits=14)),
                ('peak_margin_utilized', models.DecimalField(decimal_places=2, default=0.0, help_text='Peak margin utilized during session', max_digits=14)),
                ('closed_trades_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot of all closed trade pairs with prices, timestamps & PnL')),
                ('equity_curve_snapshot', models.JSONField(blank=True, default=list, help_text='Time-series data points for session equity curve chart')),
                ('orders_snapshot', models.JSONField(blank=True, default=list, help_text='Raw orders state captured from mock broker')),
                ('positions_snapshot', models.JSONField(blank=True, default=list, help_text='Raw positions state captured from mock broker')),
                ('calendar_heatmap_snapshot', models.JSONField(blank=True, default=dict, help_text='Daily PnL map for calendar heatmap visualization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_snapshots', to='trade_config.usertradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_session_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Simulation Session Snapshot',
                'verbose_name_plural': 'Simulation Session Snapshots',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
