# Generated by Django 5.2.14 on 2026-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0005_brokermaster_usertradingaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertradingaccount',
            name='api_key',
            field=models.TextField(blank=True, help_text='API Key / Access Token', null=True),
        ),
        migrations.AlterField(
            model_name='usertradingaccount',
            name='app_id',
            field=models.TextField(blank=True, help_text='App ID / Secret Key', null=True),
        ),
        migrations.AlterField(
            model_name='usertradingaccount',
            name='broker_client_id',
            field=models.CharField(blank=True, help_text='Broker Client ID / User ID', max_length=255, null=True),
        ),
    ]
