# Generated by Django 5.2.14 on 2026-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0005_simulationsessionsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestrategy',
            name='strategy_name',
            field=models.CharField(choices=[('quant_engine', 'Go Quantitative Rule Engine (ORB / SMC / Momentum)'), ('orb_momentum', 'Opening Range Breakout (ORB 15m) & Momentum'), ('ict_smc', 'ICT Smart Money Concepts (SMC v3)'), ('hft_scalp', 'High-Frequency Micro-Scalp (HFT 1:2.0)'), ('macd_ict_hybrid', 'Advanced HTF MACD + ICT Hybrid (1:2.0 High Winrate)'), ('volume_amd', 'Volume + AMD (Accumulation, Manipulation, Distribution)')], default='quant_engine', max_length=50),
        ),
    ]
