# Generated by Django 5.2.14 on 2026-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0006_alter_usertradingaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_account_id',
            field=models.CharField(blank=True, help_text='Forex broker account / sub-account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_broker_api_key',
            field=models.TextField(blank=True, help_text='Rithmic / OANDA / CME API Key for Forex/Futures execution', null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_contract_size',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Contract/lot size for the selected CME Micro instrument (e.g. 10 for MGC)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_instrument',
            field=models.CharField(blank=True, choices=[('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], help_text='CME Micro Futures instrument (e.g. MGC, M6E, MNQ)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_max_contracts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Maximum number of contracts allowed per trade entry', null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='forex_tick_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Value per tick in USD (e.g. $1 for MGC, $1.25 for MES)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='market_type',
            field=models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Market segment: INDEX/F&O (India) or FOREX/Futures (CME Micros)', max_length=20),
        ),
    ]
