# Generated by Django 5.2.14 on 2026-10-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0007_alter_dailyportfoliosnapshot_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='backtest_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='estimated_brokerage',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forecast_status',
        ),
        migrations.RemoveField(
            model_name='usertradingaccount',
            name='is_trader_active',
        ),
    ]
