# Generated by Django 5.2.14 on 2026-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0007_add_market_type_and_forex_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_loss_status',
            field=models.BooleanField(default=False, help_text='Enable maximum loss limit rule for auto-freeze'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_profit_status',
            field=models.BooleanField(default=False, help_text='Enable maximum profit limit rule'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed loss limit before auto-freeze triggers', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_profit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target max profit limit for the session', max_digits=12, null=True),
        ),
    ]
