# Generated by Django 5.2.14 on 2026-08-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0008_tradeexecconfig_max_loss_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='default_lot_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Default lot size to use when auto lot status is disabled'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='default_risk_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage (%)'), ('fixed_amount', 'Fixed Amount (₹/$)'), ('points', 'Points')], default='percentage', help_text='Risk calculation mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='default_risk_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Default risk value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='forex_contract_size',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Contract/lot size for selected CME instrument', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='forex_instrument',
            field=models.CharField(blank=True, choices=[('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], help_text='CME Micro Futures instrument', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='forex_max_contracts',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Max contracts allowed per trade entry', null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='forex_tick_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Value per tick in USD (e.g. $1 MGC, $1.25 MES)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='layer_add_in_lot_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of additional lots to add per layer entry'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='layer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage step/distance required per layer', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='market_type',
            field=models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Market segment', max_length=20),
        ),
    ]
