# Generated by Django 5.2.14 on 2026-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0009_alter_tradeexecconfig_default_lot_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradingaccount',
            name='keep_alive',
            field=models.BooleanField(default=False, help_text='Auto-refresh access token every 8 hours'),
        ),
        migrations.AddField(
            model_name='usertradingaccount',
            name='last_token_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful token renewal', null=True),
        ),
    ]
