# Generated by Django 5.2.14 on 2026-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0009_alter_livestrategy_strategy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='auto_lot_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='auto_sl_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_lot_size',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_risk_type',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_risk_value',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_add_in_lot_count',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_percentage',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_status',
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max allowed daily loss percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_loss_reference',
            field=models.CharField(blank=True, choices=[('OPENING_BALANCE', 'Day Opening Balance'), ('AVAILABLE_CAPITAL', 'Current Available Margin / Capital')], default='OPENING_BALANCE', help_text='Capital baseline', max_length=20),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_loss_type',
            field=models.CharField(choices=[('AMOUNT', 'Amount-Based (Fixed Currency)'), ('PERCENTAGE', 'Percentage-Based (%)')], default='AMOUNT', help_text='Max loss limit calculation mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max loss limit amount before auto-freeze triggers', max_digits=12, null=True),
        ),
    ]
