# Generated by Django 5.2.14 on 2026-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0009_alter_livestrategy_strategy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='final_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000.0, help_text='Level 2 hard day loss threshold', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='final_loss_status',
            field=models.BooleanField(default=True, help_text='Enable Level 2 Hard Loss Limit for full-day account freeze'),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='primary_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, help_text='Level 1 warning loss threshold', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecconfig',
            name='primary_loss_status',
            field=models.BooleanField(default=True, help_text='Enable Level 1 Warning Loss Limit for soft auto-freeze'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='auto_lot_status',
            field=models.BooleanField(blank=True, default=False, help_text='Legacy auto lot toggle'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='auto_sl_status',
            field=models.BooleanField(blank=True, default=False, help_text='Legacy auto stop loss toggle'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='default_lot_size',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Legacy default lot size', null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='default_risk_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Legacy risk value', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='layer_add_in_lot_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Legacy layer lots', null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='layer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Legacy layer percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='layer_status',
            field=models.BooleanField(blank=True, default=False, help_text='Legacy layering toggle'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy max loss limit (synced to final_loss_limit)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_loss_status',
            field=models.BooleanField(default=True, help_text='Legacy max loss limit status (synced to final_loss_status)'),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='max_profit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target max profit limit for session', max_digits=12, null=True),
        ),
    ]
