# Generated by Django 5.2.14 on 2026-09-06 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0031_backtesttask_auto_risk_management_and_more'),
        ('trade_config', '0010_usertradingaccount_keep_alive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Live Strategy Deployment Name', max_length=255)),
                ('strategy_name', models.CharField(choices=[('tensortrade_rl', 'TensorTrade RL (Deep Reinforcement Learning)')], default='tensortrade_rl', max_length=50)),
                ('index_name', models.CharField(default='NIFTY', help_text='Target trading asset (e.g. NIFTY, BANKNIFTY)', max_length=50)),
                ('market_type', models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Market segment', max_length=20)),
                ('allocated_capital', models.DecimalField(decimal_places=2, default=100000.0, help_text='Allocated capital in INR', max_digits=12)),
                ('frozen_rules_snapshot', models.JSONField(blank=True, default=list, help_text='Immutable snapshot of rules at deployment')),
                ('frozen_parameters', models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of parameters at deployment')),
                ('is_active', models.BooleanField(default=False, help_text='Live execution enabled toggle (initially False)')),
                ('execution_mode', models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account')], default='LIVE', max_length=20)),
                ('status', models.CharField(choices=[('STANDBY', 'Standby'), ('ACTIVE', 'Active / Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='STANDBY', max_length=20)),
                ('realtime_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Realtime session PnL', max_digits=12)),
                ('total_trades', models.PositiveIntegerField(default=0, help_text='Total live trades executed')),
                ('last_signal_at', models.DateTimeField(blank=True, help_text='Timestamp of last signal', null=True)),
                ('backtest_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_deployments', to='backtest.backtesttask', verbose_name='Source Backtest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('trading_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_strategies', to='trade_config.usertradingaccount', verbose_name='Target Trading Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_strategies', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Live Strategy',
                'verbose_name_plural': 'Live Strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
