# Generated by Django 5.2.14 on 2026-10-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0010_tradeexecconfig_final_loss_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='api_response_log',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='auto_lot_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='auto_sl_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_lot_size',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_risk_type',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='default_risk_value',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='execution_remarks',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='execution_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_add_in_lot_count',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_percentage',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='layer_status',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='realtime_pnl',
        ),
    ]
