# Generated by Django 5.2.14 on 2026-10-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0011_remove_tradeexecconfig_api_response_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_account_id',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_broker_api_key',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_contract_size',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_instrument',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_max_contracts',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='forex_tick_value',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='max_loss_limit',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='max_loss_status',
        ),
    ]
