# Generated by Django 5.2.14 on 2026-09-08 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0011_livestrategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account')], default='SANDBOX', help_text='Execution Mode', max_length=20)),
                ('date', models.DateField(db_index=True, help_text='Calendar trading date')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Starting day balance', max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Ending day balance', max_digits=12)),
                ('gross_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross trading PnL', max_digits=12)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Net PnL after charges', max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Realized PnL', max_digits=12)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Open positions PnL', max_digits=12)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Brokerage and regulatory charges', max_digits=12)),
                ('margin_utilized', models.DecimalField(decimal_places=2, default=0.0, help_text='Peak margin utilized during day', max_digits=12)),
                ('total_trades', models.PositiveIntegerField(default=0, help_text='Total trades executed')),
                ('winning_trades', models.PositiveIntegerField(default=0, help_text='Winning trade count')),
                ('losing_trades', models.PositiveIntegerField(default=0, help_text='Losing trade count')),
                ('telemetry_snapshot', models.JSONField(blank=True, default=dict, help_text='Full day-end telemetry JSON snapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='trade_config.usertradingaccount', verbose_name='Trading Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_portfolio_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Daily Portfolio Snapshot',
                'verbose_name_plural': 'Daily Portfolio Snapshots',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'trading_account', 'date'), name='unique_user_account_daily_snapshot')],
            },
        ),
    ]
