# Generated by Django 5.2.14 on 2026-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0012_remove_tradeexecconfig_forex_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecconfig',
            name='max_loss_status',
            field=models.BooleanField(default=True, help_text='Master toggle to enable Account Guardian circuit breaker'),
        ),
    ]
