# Generated by Django 5.2.14 on 2026-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0012_dailyportfoliosnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyportfoliosnapshot',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account'), ('MOCK', 'Mock Emulator Account')], default='SANDBOX', help_text='Execution Mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestrategy',
            name='execution_mode',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account'), ('MOCK', 'Mock Emulator Account')], default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeexecconfig',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account'), ('MOCK', 'Mock Emulator Account')], default='SANDBOX', help_text='Target execution account mode (LIVE / SANDBOX)', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertradingaccount',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live Account'), ('SANDBOX', 'Sandbox Account'), ('MOCK', 'Mock Emulator Account')], default='SANDBOX', help_text='Account environment mode (LIVE / SANDBOX)', max_length=20),
        ),
    ]
