# Generated by Django 5.2.14 on 2026-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0013_alter_dailyportfoliosnapshot_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestrategy',
            name='strategy_name',
            field=models.CharField(choices=[('quant_engine', 'Go Quantitative Rule Engine (ORB / SMC / Momentum)'), ('orb_momentum', 'Opening Range Breakout (ORB 15m) & Momentum'), ('ict_smc', 'ICT Smart Money Concepts (SMC v3)'), ('tensortrade_rl', 'Legacy Quantitative Engine (Deprecated)')], default='tensortrade_rl', max_length=50),
        ),
    ]
