# Generated by Django 5.2.14 on 2026-10-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_config', '0014_alter_livestrategy_strategy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestrategy',
            name='frozen_rules_snapshot',
        ),
        migrations.RemoveField(
            model_name='livestrategy',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='max_profit_limit',
        ),
        migrations.RemoveField(
            model_name='tradeexecconfig',
            name='max_profit_status',
        ),
    ]
