# Generated by Django 5.2.14 on 2026-08-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0005_delete_backtesttask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('strategy_name', models.CharField(choices=[('ict_smc', 'ICT / SMC (Order Block & FVG)'), ('gamma_blast', 'Expiry Gamma Blast (0DTE)'), ('candle_3pm', '3:00 PM Breakout Candle')], default='ict_smc', max_length=50)),
                ('index_name', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty')], default='NIFTY', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.FloatField(default=100000.0, help_text='Starting capital in INR')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Strategy-specific custom parameters')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Summary KPIs: Net PnL, Win Rate, Max Drawdown, Sharpe Ratio')),
                ('result_file_path', models.CharField(blank=True, help_text='Path to detailed trade logs parquet file', max_length=500, null=True)),
                ('error_logs', models.TextField(blank=True, null=True)),
                ('backup_task', models.ForeignKey(blank=True, help_text='Optional selected backup dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='market.marketbackuptask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backtest Task',
                'verbose_name_plural': 'Backtest Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
