# Generated by Django 5.2.14 on 2026-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Rule Name e.g. Intraday Only (Auto Square-off 15:15)', max_length=120)),
                ('market_type', models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)'), ('ALL', 'All Markets (Shared)')], default='ALL', help_text='Target market segment: Index F&O, Forex Futures, or Shared across all markets.', max_length=20)),
                ('rule_type', models.CharField(choices=[('intraday', 'Intraday Only'), ('gamma_blast', 'Gamma Blast (0DTE Expiry)'), ('morning_trend', 'Morning Trend Capture'), ('gap_openings', 'Overnight Gap Prediction (BTST / STBT)'), ('risk_management', 'Strict SL & TP Placement'), ('retest_limit', 'Retest Limit Entry (No Market Orders)'), ('trendline_retest', 'Trendline Breakout & Retest'), ('india_vix', 'India VIX Volatility Regime'), ('loss_rca', 'Stop-Loss RCA & Learning Engine'), ('atr_noise_filter', 'Dynamic ATR Volatility Buffer (Anti-Noise)'), ('candle_close_sl', 'Candle Close SL & Anti-Wick Guardrail'), ('liquidity_sweep', 'Liquidity Sweep & False Breakout Filter (SMC)'), ('pdh_pdl', 'PDH & PDL Breakout / Liquidity Sweep Filter'), ('ict_smc_matrix', 'ICT Institutional Smart Money (Killzone, MSS, FVG & OTE)'), ('ict_smc_v2', 'ICT v2: Confirmed OTE Retest & Mitigation (Zero Drawdown)'), ('ict_smc_v3', 'ICT v3: Institutional Displacement, HTF Bias & Liquidity Sweep Engine'), ('ict_smc_v4_layering', 'ICT v4: Multi-Timeframe CHoCH & 0.5/0.705 Dual Layering OTE'), ('morning_macd_retest', 'Morning 3-Min HTF & Option MACD Retest'), ('forex_cvd_divergence', 'Forex CVD (Cumulative Volume Delta) Divergence'), ('forex_dom_absorption', 'Forex Level-10 DOM Depth & Iceberg Absorption'), ('forex_killzone_delta', 'Forex London & NY Killzone Order Flow Surge'), ('forex_smc_displacement', 'Forex SMC Displacement & FVG Retest'), ('custom_prompt', 'AI Prompt Directive'), ('technical', 'Technical / Indicator'), ('momentum_guardrail', 'Professional Intraday Trend & Momentum Guardrails'), ('algo_micro_scalp', 'Institutional Micro-Scalp & Dynamic Risk Guard'), ('momentum_scalp', 'Momentum Scalp 1:2.5 (EMA 9/21 + ORB)')], default='intraday', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the trading rule')),
                ('prompt_directive', models.TextField(blank=True, default='', help_text='Natural language prompt directive for Go Quantitative Strategy Engine')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON parameters for rule constraints')),
                ('is_system_preset', models.BooleanField(default=False, help_text='Protected system default preset rule')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Backtest Rule',
                'verbose_name_plural': 'Backtest Rules',
                'ordering': ['-is_system_preset', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('applied_rules', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('execution_duration_sec', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Backtest Run Log',
                'verbose_name_plural': 'Backtest Run Logs',
                'ordering': ['-run_number'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('market_type', models.CharField(choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')], default='INDEX_FO', help_text='Target market segment: INDEX/F&O (India) or FOREX/Futures (CME Micros)', max_length=20)),
                ('use_macro_assist', models.BooleanField(default=False, help_text='Enable Gemini AI Macro Assist in RL observation space')),
                ('macro_timeframe', models.CharField(blank=True, choices=[('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour (Recommended)'), ('1d', '1 Day (EOD)')], default='1h', help_text='Macro timeframe (default 1h)', max_length=10, null=True)),
                ('enable_ai_lot_sizing', models.BooleanField(default=False, help_text='Enable AI Macro Dynamic Position Sizing')),
                ('auto_risk_management', models.BooleanField(default=True, help_text='Enforce automatic risk management and capital utilization limits')),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum risk percentage of capital per trade', max_digits=5)),
                ('max_capital_utilization_pct', models.DecimalField(decimal_places=2, default=60.0, help_text='Maximum capital margin utilization percentage', max_digits=5)),
                ('max_lots_cap', models.PositiveIntegerField(default=10, help_text='Hard ceiling on concurrent lots count')),
                ('strategy_name', models.CharField(choices=[('quant_engine', 'Go Quantitative Rule Engine (ORB / SMC / Momentum)'), ('orb_momentum', 'Opening Range Breakout (ORB 15m) & Momentum'), ('ict_smc', 'ICT Smart Money Concepts (SMC v3)')], default='quant_engine', max_length=50)),
                ('index_name', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('SENSEX', 'BSE Sensex'), ('GIFTNIFTY', 'GIFT Nifty'), ('INDIAVIX', 'India VIX'), ('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], default='NIFTY', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.FloatField(default=100000.0, help_text='Starting capital in INR')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Strategy-specific custom parameters')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Summary KPIs: Net PnL, Win Rate, Max Drawdown, Sharpe Ratio')),
                ('result_file_path', models.CharField(blank=True, help_text='Path to detailed trade logs (JSON) file', max_length=500, null=True)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Full backtest result including trades', null=True)),
                ('error_logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backtest Task',
                'verbose_name_plural': 'Backtest Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Strategy Name e.g. 3:00 PM Institutional Breakout', max_length=100)),
                ('code_name', models.CharField(help_text='Code identifier matching Go implementation e.g. candle_3pm', max_length=50, unique=True)),
                ('category', models.CharField(default='Breakout / Momentum', help_text='e.g. Breakout, 0DTE Expiry, Smart Money Concepts', max_length=50)),
                ('target_index', models.CharField(default='NIFTY, BANKNIFTY', help_text='Compatible Index symbols', max_length=100)),
                ('description', models.TextField(help_text='Detailed overview of strategy logic')),
                ('go_file_path', models.CharField(default='go-app/strategies/candle_3pm.go', help_text='Path to Go implementation file', max_length=255)),
                ('default_parameters', models.JSONField(blank=True, default=dict, help_text='Default strategy parameters JSON')),
                ('user_manual', models.TextField(blank=True, default='', help_text='User manual & step-by-step trading rules')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trading Strategy',
                'verbose_name_plural': 'Trading Strategies',
                'ordering': ['id'],
            },
        ),
    ]
