# Generated by Django 5.2.14 on 2026-09-19 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtestrunlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='backup_task',
            field=models.ForeignKey(blank=True, help_text='Optional selected backup dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='market.marketbackuptask'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='macro_backup_task',
            field=models.ForeignKey(blank=True, help_text='Linked Macro Assist Parquet dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_backtests', to='market.marketbackuptask'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='rules',
            field=models.ManyToManyField(blank=True, help_text='Selected Strategy Rules for RL simulation', related_name='backtests', to='backtest.backtestrule'),
        ),
        migrations.AddField(
            model_name='backtestrunlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='backtest.backtesttask'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
