# Generated by Django 5.2.14 on 2026-08-13 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Strategy Name e.g. 3:00 PM Institutional Breakout', max_length=100)),
                ('code_name', models.CharField(help_text='Code identifier matching Go implementation e.g. candle_3pm', max_length=50, unique=True)),
                ('category', models.CharField(default='Breakout / Momentum', help_text='e.g. Breakout, 0DTE Expiry, Smart Money Concepts', max_length=50)),
                ('target_index', models.CharField(default='NIFTY, BANKNIFTY', help_text='Compatible Index symbols', max_length=100)),
                ('description', models.TextField(help_text='Detailed overview of strategy logic')),
                ('go_file_path', models.CharField(default='go-app/strategies/candle_3pm.go', help_text='Path to Go implementation file', max_length=255)),
                ('default_parameters', models.JSONField(blank=True, default=dict, help_text='Default strategy parameters JSON')),
                ('user_manual', models.TextField(blank=True, default='', help_text='User manual & step-by-step trading rules')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Strategy',
                'verbose_name_plural': 'Trading Strategies',
                'ordering': ['id'],
            },
        ),
    ]
