# Generated by Django 5.2.14 on 2026-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_tradingstrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='index_name',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('INDIAVIX', 'India VIX')], default='NIFTY', max_length=50),
        ),
    ]
