# Generated by Django 5.2.14 on 2026-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_alter_backtesttask_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='strategy_name',
            field=models.CharField(choices=[('ict_smc', 'ICT / SMC (Order Block & FVG)'), ('gamma_blast', 'Expiry Gamma Blast (0DTE)'), ('candle_3pm', '3:00 PM Breakout Candle'), ('tensortrade_rl', 'TensorTrade RL (Deep Reinforcement Learning)')], default='ict_smc', max_length=50),
        ),
    ]
