# Generated by Django 5.2.14 on 2026-08-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_alter_backtesttask_strategy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='strategy_name',
            field=models.CharField(choices=[('tensortrade_rl', 'TensorTrade RL (Deep Reinforcement Learning)')], default='tensortrade_rl', max_length=50),
        ),
    ]
