# Generated by Django 5.2.14 on 2026-08-22 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_backtesttask_results_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Rule Name e.g. Intraday Only (Auto Square-off 15:15)', max_length=120)),
                ('rule_type', models.CharField(choices=[('intraday', 'Intraday Only'), ('gamma_blast', 'Gamma Blast (0DTE Expiry)'), ('morning_trend', 'Morning Trend Capture'), ('gap_openings', 'Gap Up / Gap Down'), ('custom_prompt', 'AI Prompt Directive'), ('technical', 'Technical / Indicator')], default='intraday', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the trading rule')),
                ('prompt_directive', models.TextField(blank=True, default='', help_text='Natural language prompt directive for AI TensorTrade RL Engine')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON parameters for rule constraints')),
                ('is_system_preset', models.BooleanField(default=False, help_text='Protected system default preset rule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backtest Rule',
                'verbose_name_plural': 'Backtest Rules',
                'ordering': ['-is_system_preset', 'id'],
            },
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='rules',
            field=models.ManyToManyField(blank=True, help_text='Selected Strategy Rules for RL simulation', related_name='backtests', to='backtest.backtestrule'),
        ),
    ]
