# Generated by Django 5.2.14 on 2026-08-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0007_backtestrule_backtesttask_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrule',
            name='rule_type',
            field=models.CharField(choices=[('intraday', 'Intraday Only'), ('gamma_blast', 'Gamma Blast (0DTE Expiry)'), ('morning_trend', 'Morning Trend Capture'), ('gap_openings', 'Overnight Gap Prediction (BTST / STBT)'), ('custom_prompt', 'AI Prompt Directive'), ('technical', 'Technical / Indicator')], default='intraday', max_length=50),
        ),
    ]
