# Generated by Django 5.2.14 on 2026-10-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0007_alter_backtestrule_rule_type_and_more'),
        ('market', '0006_marketbackuptask_use_30_days_1s'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='use_vix_assist',
            field=models.BooleanField(default=False, help_text='Enable India VIX volatility regime assist in backtest evaluation'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='vix_backup_task',
            field=models.ForeignKey(blank=True, help_text='Linked India VIX dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vix_backtests', to='market.marketbackuptask'),
        ),
    ]
