# Generated by Django 5.2.14 on 2026-10-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0010_alter_backtestrule_rule_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtesttask',
            name='rules',
        ),
        migrations.DeleteModel(
            name='BacktestRule',
        ),
    ]
