# Generated by Django on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0018_alter_backtestrule_rule_type_and_seed_morning_macd_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrule',
            name='market_type',
            field=models.CharField(
                choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)'), ('ALL', 'All Markets (Shared)')],
                default='ALL',
                help_text='Target market segment: Index F&O, Forex Futures, or Shared across all markets.',
                max_length=20
            ),
        ),
    ]
