# Generated by Django on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0021_update_index_rules_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='market_type',
            field=models.CharField(
                choices=[('INDEX_FO', 'INDEX / F&O (India — Nifty, BankNifty…)'), ('FOREX_FUTURES', 'FOREX / Futures (CME Micro Futures)')],
                default='INDEX_FO',
                help_text='Target market segment: INDEX/F&O (India) or FOREX/Futures (CME Micros)',
                max_length=20
            ),
        ),
    ]
