# Generated by Django 5.2.14 on 2026-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0023_seed_liquidity_sweep_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='index_name',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('FINNIFTY', 'Fin Nifty'), ('MIDCPNIFTY', 'Midcp Nifty'), ('INDIAVIX', 'India VIX'), ('MGC', 'XAUUSD / Gold  →  MGC  (Micro Gold)'), ('M6E', 'EURUSD          →  M6E  (Micro Euro FX)'), ('M6J', 'USDJPY          →  M6J  (Micro Japanese Yen)'), ('MYM', 'US30 / Dow      →  MYM  (Micro Dow)'), ('MNQ', 'NAS100 / Nasdaq →  MNQ  (Micro Nasdaq)'), ('MES', 'SPX500 / S&P    →  MES  (Micro S&P 500)'), ('MCL', 'USOIL / Crude   →  MCL  (Micro Crude Oil)')], default='NIFTY', max_length=50),
        ),
    ]
