# Generated by Django 5.2.14 on 2026-09-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0025_alter_backtesttask_index_name'),
        ('market', '0010_marketbackuptask_is_macro_assist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='macro_backup_task',
            field=models.ForeignKey(blank=True, help_text='Linked Macro Assist Parquet dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macro_backtests', to='market.marketbackuptask'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='macro_timeframe',
            field=models.CharField(blank=True, choices=[('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour (Recommended)'), ('1d', '1 Day (EOD)')], default='1h', help_text='Macro timeframe (default 1h)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='use_macro_assist',
            field=models.BooleanField(default=False, help_text='Enable Gemini AI Macro Assist in RL observation space'),
        ),
    ]
