# Generated by Django 5.2.14 on 2026-09-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0026_backtesttask_macro_backup_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('applied_rules', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('execution_duration_sec', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='backtest.backtesttask')),
            ],
            options={
                'verbose_name': 'Backtest Run Log',
                'verbose_name_plural': 'Backtest Run Logs',
                'ordering': ['-run_number'],
            },
        ),
    ]
