# Generated by Django 5.2.14 on 2026-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0029_alter_backtestrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrule',
            name='rule_type',
            field=models.CharField(choices=[('intraday', 'Intraday Only'), ('gamma_blast', 'Gamma Blast (0DTE Expiry)'), ('morning_trend', 'Morning Trend Capture'), ('gap_openings', 'Overnight Gap Prediction (BTST / STBT)'), ('risk_management', 'Strict SL & TP Placement'), ('retest_limit', 'Retest Limit Entry (No Market Orders)'), ('trendline_retest', 'Trendline Breakout & Retest'), ('india_vix', 'India VIX Volatility Regime'), ('loss_rca', 'Stop-Loss RCA & Learning Engine'), ('atr_noise_filter', 'Dynamic ATR Volatility Buffer (Anti-Noise)'), ('candle_close_sl', 'Candle Close SL & Anti-Wick Guardrail'), ('liquidity_sweep', 'Liquidity Sweep & False Breakout Filter (SMC)'), ('pdh_pdl', 'PDH & PDL Breakout / Liquidity Sweep Filter'), ('ict_smc_matrix', 'ICT Institutional Smart Money (Killzone, MSS, FVG & OTE)'), ('ict_smc_v2', 'ICT v2: Confirmed OTE Retest & Mitigation (Zero Drawdown)'), ('ict_smc_v3', 'ICT v3: Institutional Displacement, HTF Bias & Liquidity Sweep Engine'), ('morning_macd_retest', 'Morning 3-Min HTF & Option MACD Retest'), ('forex_cvd_divergence', 'Forex CVD (Cumulative Volume Delta) Divergence'), ('forex_dom_absorption', 'Forex Level-10 DOM Depth & Iceberg Absorption'), ('forex_killzone_delta', 'Forex London & NY Killzone Order Flow Surge'), ('forex_smc_displacement', 'Forex SMC Displacement & FVG Retest'), ('custom_prompt', 'AI Prompt Directive'), ('technical', 'Technical / Indicator'), ('momentum_guardrail', 'Professional Intraday Trend & Momentum Guardrails')], default='intraday', max_length=50),
        ),
    ]
