# Generated by Django 5.2.14 on 2026-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0030_alter_backtestrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='auto_risk_management',
            field=models.BooleanField(default=True, help_text='Enforce automatic risk management and capital utilization limits'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='enable_ai_lot_sizing',
            field=models.BooleanField(default=False, help_text='Enable AI Macro Dynamic Position Sizing'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='max_capital_utilization_pct',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Maximum capital margin utilization percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='max_lots_cap',
            field=models.PositiveIntegerField(default=10, help_text='Hard ceiling on concurrent lots count'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='max_risk_per_trade_pct',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum risk percentage of capital per trade', max_digits=5),
        ),
    ]
