# Generated by Django 5.2.14 on 2026-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0034_alter_backtesttask_strategy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrule',
            name='prompt_directive',
            field=models.TextField(blank=True, default='', help_text='Natural language prompt directive for Go Quantitative Strategy Engine'),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='strategy_name',
            field=models.CharField(choices=[('quant_engine', 'Go Quantitative Rule Engine (ORB / SMC / Momentum)'), ('orb_momentum', 'Opening Range Breakout (ORB 15m) & Momentum'), ('ict_smc', 'ICT Smart Money Concepts (SMC v3)')], default='quant_engine', max_length=50),
        ),
    ]
