# Generated by Django 5.2.14 on 2026-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiverJob',
        ),
    ]
